# Generated by Django 5.0.7 on 2024-08-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
