# Generated by Django 5.0.7 on 2024-08-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_message_sender_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='average_rating',
            field=models.IntegerField(default=0),
        ),
    ]
